<a href="https://colab.research.google.com/github/ms-daniel/II-Projeto-IA/blob/main/II_Projeto_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#II Projeto de Inteligência Artificial

Nesse projeto iremos utilizar rede neural perceptron juntamento com os classificadores KNN e One Rule 


In [ ]:
import pandas as pd
import numpy as ny


def mensagem(msg, baseTreinamento):
  print('-'*40)
  print(msg)
  print('-'*40)
  print(baseTreinamento)
  print('-'*40)

#url = input("Insira a base de dados: ")
url = 'https://raw.githubusercontent.com/lauro-ss/Exercicio-IA-Rede-Neural/main/base_de_dados_diabetes.csv'

base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values

#número de linhas e colunas do arquivo
row_count, column_count = base_Treinamento.shape


mensagem('Dados do arquivo', base_Treinamento)

inicio = column_count - column_count
#Por padrão a última coluna é sempre a coluna de resultados
fim = column_count-1

atributosDeEntrada = base_Treinamento[:, inicio:fim]

mensagem('Atributos de Entrada', atributosDeEntrada)

classificacaoSupervisionada = base_Treinamento[:, fim]

mensagem('Classificação Supervisionada', classificacaoSupervisionada)
#é necessário realizar o tratamento dos atributos de entrada de acordo com o arquivo que será passado como a base de treinamento
#ou seja, verificar quais colunas realmente interessam para a realização do treinamento e, quais devem ser ignoradas 


----------------------------------------
Dados do arquivo
----------------------------------------
[[  6.    148.     72.    ...   0.627  50.      1.   ]
 [  1.     85.     66.    ...   0.351  31.      0.   ]
 [  8.    183.     64.    ...   0.672  32.      1.   ]
 ...
 [  5.    121.     72.    ...   0.245  30.      0.   ]
 [  1.    126.     60.    ...   0.349  47.      1.   ]
 [  1.     93.     70.    ...   0.315  23.      0.   ]]
----------------------------------------
----------------------------------------
Atributos de Entrada
----------------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------------------
----------------------------------------
Cla

# Normalização

In [ ]:
from sklearn import preprocessing
# Normalizar atributos de entrada entre [0,1]
# min_max será o transformador que irá normalizar os atributos de entrada
# e também os atributos a serem utilizados como testes (células seguintes...)
min_max = preprocessing.MinMaxScaler()
atributos_norm = min_max.fit_transform(base_Treinamento[:,:fim])
# Testar sem normalização dos dados
#atributos_norm = base_Treinamento[:,:8]
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)
diagnostico_norm = base_Treinamento[:, fim]
print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

## Treinamento do Perceptron

In [ ]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.2f' % (modelo.score(atributos_norm, diagnostico_norm) * 100) + '%')


Acurácia: 73.57%


## Treinamento do KNN (K-Nearest Neighbor)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
# Treinamento do Knn a partir dos atributos de entrada e classificações com K=3
modelo = KNeighborsClassifier(n_neighbors=1)
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.2f' % (modelo.score(atributos_norm, diagnostico_norm) * 100) + '%')

Acurácia: 100.00%


## Treinamento do 1R

In [ ]:
!pip install mlxtend  

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
#Treinamento do 1R
#from sklearn.model_selection import train_test_split
#from mlxtend.classifier import OneRClassifier

#oneRule = OneRClassifier()

#oneRule.fit(atributos_norm, diagnostico_norm)

#print('Acurácia: %.2f' % (oneRule.score(atributos_norm, diagnostico_norm) * 100) + '%')